# Prediction of breast cancer using Wisconsin breast cancer Dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
pwd


'C:\\Users\\euise\\Documents\\python practice\\wisconsin_breast_cancer'

In [2]:
import os

In [3]:
data = pd.read_csv('data.csv')

In [4]:
data.head(10)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   
5    843786         M        12.45         15.70           82.57      477.1   
6    844359         M        18.25         19.98          119.60     1040.0   
7  84458202         M        13.71         20.83           90.20      577.9   
8    844981         M        13.00         21.82           87.50      519.8   
9  84501001         M        12.46         24.04           83.97      475.9   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760         0.30010              0.14710   
1          0.08474           0.07864         0.08690              0.07017   
2          0.10960           0.15990         0.19740              0.12790   
3          0.14250           0.28390         0.24140              0.10520   
4          0.10030           0.13280         0.19800              0.10430   
5          0.12780           0.17000         0.15780              0.08089   
6          0.09463           0.10900         0.11270              0.07400   
7          0.11890           0.16450         0.09366              0.05985   
8          0.12730           0.19320         0.18590              0.09353   
9          0.11860           0.23960         0.22730              0.08543   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   
5  ...          23.75           103.40       741.6            0.1791   
6  ...          27.66           153.20      1606.0            0.1442   
7  ...          28.14           110.60       897.0            0.1654   
8  ...          30.73           106.20       739.3            0.1703   
9  ...          40.68            97.65       711.4            0.1853   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   
5             0.5249           0.5355                0.1741          0.3985   
6             0.2576           0.3784                0.1932          0.3063   
7             0.3682           0.2678                0.1556          0.3196   
8             0.5401           0.5390                0.2060          0.4378   
9             1.0580           1.1050                0.2210          0.4366   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  
5                  0.12440          NaN  
6                  0.08368          NaN  
7                  0.11510          NaN  
8                  0.10720          NaN  
9                  0.20750          NaN  

[10 rows x 33 columns]

In [5]:
data.shape

(569, 33)

In [6]:
data.dtypes

id                           int64
diagnosis                   object
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst     

In [7]:
data.drop(['Unnamed: 32','id'],axis=1,inplace=True)

In [8]:
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [9]:
data['diagnosis'] = [1 if each =='M' else 0 for each in data['diagnosis']]

In [10]:
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          1        17.99         10.38          122.80     1001.0   
1          1        20.57         17.77          132.90     1326.0   
2          1        19.69         21.25          130.00     1203.0   
3          1        11.42         20.38           77.58      386.1   
4          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [11]:
y = data['diagnosis']
y

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64

In [12]:
X = data.iloc[:,1:]

In [13]:
X


radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [14]:
type(X)


pandas.core.frame.DataFrame

In [15]:
type(y)

pandas.core.series.Series

In [16]:
print(X.shape)
print(y.shape)

(569, 30)
(569,)


In [17]:
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=122)

In [19]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(455, 30)
(114, 30)
(455,)
(114,)


In [20]:
y_train.value_counts()

0    278
1    177
Name: diagnosis, dtype: int64

In [21]:
print(y_train.value_counts()/y_train.shape[0])

0    0.610989
1    0.389011
Name: diagnosis, dtype: float64


In [22]:
print(y_test.value_counts()/y_test.shape[0])

0    0.692982
1    0.307018
Name: diagnosis, dtype: float64


In [23]:
print(data['diagnosis'].value_counts()/len(data))

0    0.627417
1    0.372583
Name: diagnosis, dtype: float64


## Support Vector Machine

In [24]:
import numpy as np
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix
from sklearn import svm
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score,f1_score

### Apply various kernel functions and compare accuracy

In [25]:
kernels = ['poly','rbf','sigmoid','linear']

for k in kernels:
    svclassifier = SVC(kernel = k, C=1,random_state=0)
    svclassifier.fit(X_train,y_train)
    y_pred = svclassifier.predict(X_test)
    print("Kernel is",k)
    print(confusion_matrix(y_test,y_pred))
    print("accuracy",accuracy_score(y_test,y_pred))
    print('F1 score',f1_score(y_test,y_pred))
    print('\n --------------------- \n')
          

Kernel is poly
[[78  1]
 [ 5 30]]
accuracy 0.9473684210526315
F1 score 0.909090909090909

 --------------------- 

Kernel is rbf
[[77  2]
 [ 5 30]]
accuracy 0.9385964912280702
F1 score 0.8955223880597014

 --------------------- 

Kernel is sigmoid
[[35 44]
 [31  4]]
accuracy 0.34210526315789475
F1 score 0.09638554216867469

 --------------------- 

Kernel is linear
[[76  3]
 [ 3 32]]
accuracy 0.9473684210526315
F1 score 0.9142857142857143

 --------------------- 



### Grid Search 

In [26]:
from sklearn.model_selection import GridSearchCV

param_grid ={"C":[0.1,1,10,100,1000],
            'gamma':[1,0.1,0.01,0.001,0.0001],
            'kernel':['linear']}

grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ..................C=0.1, gamma=1, kernel=linear; total time=   0.1s
[CV 2/5] END ..................C=0.1, gamma=1, kernel=linear; total time=   0.0s
[CV 3/5] END ..................C=0.1, gamma=1, kernel=linear; total time=   0.1s
[CV 4/5] END ..................C=0.1, gamma=1, kernel=linear; total time=   0.0s
[CV 5/5] END ..................C=0.1, gamma=1, kernel=linear; total time=   0.1s
[CV 1/5] END ................C=0.1, gamma=0.1, kernel=linear; total time=   0.1s
[CV 2/5] END ................C=0.1, gamma=0.1, kernel=linear; total time=   0.0s
[CV 3/5] END ................C=0.1, gamma=0.1, kernel=linear; total time=   0.1s
[CV 4/5] END ................C=0.1, gamma=0.1, kernel=linear; total time=   0.0s
[CV 5/5] END ................C=0.1, gamma=0.1, kernel=linear; total time=   0.1s
[CV 1/5] END ...............C=0.1, gamma=0.01, kernel=linear; total time=   0.1s
[CV 2/5] END ...............C=0.1, gamma=0.01, 

[CV 2/5] END .................C=1000, gamma=1, kernel=linear; total time=   7.5s
[CV 3/5] END .................C=1000, gamma=1, kernel=linear; total time=   9.1s
[CV 4/5] END .................C=1000, gamma=1, kernel=linear; total time=   1.2s
[CV 5/5] END .................C=1000, gamma=1, kernel=linear; total time=  10.3s
[CV 1/5] END ...............C=1000, gamma=0.1, kernel=linear; total time=  14.0s
[CV 2/5] END ...............C=1000, gamma=0.1, kernel=linear; total time=   7.6s
[CV 3/5] END ...............C=1000, gamma=0.1, kernel=linear; total time=   9.1s
[CV 4/5] END ...............C=1000, gamma=0.1, kernel=linear; total time=   1.3s
[CV 5/5] END ...............C=1000, gamma=0.1, kernel=linear; total time=  11.3s
[CV 1/5] END ..............C=1000, gamma=0.01, kernel=linear; total time=  14.2s
[CV 2/5] END ..............C=1000, gamma=0.01, kernel=linear; total time=   7.4s
[CV 3/5] END ..............C=1000, gamma=0.01, kernel=linear; total time=   8.9s
[CV 4/5] END ..............C

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear']},
             verbose=3)

In [27]:
print(grid.best_params_)
print(grid.best_estimator_)

{'C': 1000, 'gamma': 1, 'kernel': 'linear'}
SVC(C=1000, gamma=1, kernel='linear')


In [28]:
y_predictions = grid.predict(X_test)
print(confusion_matrix(y_test,y_predictions))
print("accuracy:",accuracy_score(y_test,y_predictions))
print('F1 score:',f1_score(y_test,y_predictions))

[[74  5]
 [ 1 34]]
accuracy: 0.9473684210526315
F1 score: 0.9189189189189189


## Decision Tree

In [26]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [27]:
train_predictions = classifier.predict(X_train)
test_predictions = classifier.predict(X_test)

In [28]:
from sklearn.metrics import f1_score,accuracy_score

# Metrics for Training set
print('Confusion matrix for training set: \n',confusion_matrix(y_train,train_predictions))
print('\n Train Data accuracy',accuracy_score(y_train,train_predictions))
print('\n Train Data f1-score for class 1 ',f1_score(y_train,train_predictions,pos_label=1))
print('\n Train Data f1-score for class 0 ',f1_score(y_train,train_predictions,pos_label=0))

# Metrics for Test set
print('\n\n ------------------------------- \n\n')
print('Confusion matrix for test set: \n',confusion_matrix(y_test,test_predictions))
print('\n Test Data accuracy',accuracy_score(y_test,test_predictions))
print('\n Test Data f1-score for class 1 ',f1_score(y_test,test_predictions,pos_label=1))
print('\n Test Data f1-score for class 0 ',f1_score(y_test,test_predictions,pos_label=0))

Confusion matrix for training set: 
 [[278   0]
 [  0 177]]

 Train Data accuracy 1.0

 Train Data f1-score for class 1  1.0

 Train Data f1-score for class 0  1.0


 ------------------------------- 


Confusion matrix for test set: 
 [[73  6]
 [ 0 35]]

 Test Data accuracy 0.9473684210526315

 Test Data f1-score for class 1  0.9210526315789475

 Test Data f1-score for class 0  0.9605263157894737


##  Naive Bayes

In [34]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB()

In [36]:
train_predictions = classifier.predict(X_train)
test_preddictions = classifier.predict(X_test)

In [37]:
# Metrics for Training set
print('Confusion matrix for training set: \n',confusion_matrix(y_train,train_predictions))
print('\n Train Data accuracy',accuracy_score(y_train,train_predictions))
print('\n Train Data f1-score for class 1 ',f1_score(y_train,train_predictions,pos_label=1))
print('\n Train Data f1-score for class 0 ',f1_score(y_train,train_predictions,pos_label=0))

# Metrics for Test set
print('\n\n ------------------------------- \n\n')
print('Confusion matrix for test set: \n',confusion_matrix(y_test,test_predictions))
print('\n Test Data accuracy',accuracy_score(y_test,test_predictions))
print('\n Test Data f1-score for class 1 ',f1_score(y_test,test_predictions,pos_label=1))
print('\n Test Data f1-score for class 0 ',f1_score(y_test,test_predictions,pos_label=0))

Confusion matrix for training set: 
 [[269   9]
 [ 19 158]]

 Train Data accuracy 0.9384615384615385

 Train Data f1-score for class 1  0.9186046511627907

 Train Data f1-score for class 0  0.9505300353356889


 ------------------------------- 


Confusion matrix for test set: 
 [[73  6]
 [ 0 35]]

 Test Data accuracy 0.9473684210526315

 Test Data f1-score for class 1  0.9210526315789475

 Test Data f1-score for class 0  0.9605263157894737


## Logistic Regression

In [42]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

C:\Users\euise\anaconda3\envs\tf2.2-gpu\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [43]:
train_predictions = classifier.predict(X_train)
test_preddictions = classifier.predict(X_test)

In [44]:
# Metrics for Training set
print('Confusion matrix for training set: \n',confusion_matrix(y_train,train_predictions))
print('\n Train Data accuracy',accuracy_score(y_train,train_predictions))
print('\n Train Data f1-score for class 1 ',f1_score(y_train,train_predictions,pos_label=1))
print('\n Train Data f1-score for class 0 ',f1_score(y_train,train_predictions,pos_label=0))

# Metrics for Test set
print('\n\n ------------------------------- \n\n')
print('Confusion matrix for test set: \n',confusion_matrix(y_test,test_predictions))
print('\n Test Data accuracy',accuracy_score(y_test,test_predictions))
print('\n Test Data f1-score for class 1 ',f1_score(y_test,test_predictions,pos_label=1))
print('\n Test Data f1-score for class 0 ',f1_score(y_test,test_predictions,pos_label=0))

Confusion matrix for training set: 
 [[268  10]
 [ 15 162]]

 Train Data accuracy 0.945054945054945

 Train Data f1-score for class 1  0.9283667621776504

 Train Data f1-score for class 0  0.9554367201426025


 ------------------------------- 


Confusion matrix for test set: 
 [[73  6]
 [ 0 35]]

 Test Data accuracy 0.9473684210526315

 Test Data f1-score for class 1  0.9210526315789475

 Test Data f1-score for class 0  0.9605263157894737


## Random Forest Classifier

In [26]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [31]:
train_predictions = classifier.predict(X_train)
test_predictions = classifier.predict(X_test)

In [32]:
# Metrics for Training set
print('Confusion matrix for training set: \n',confusion_matrix(y_train,train_predictions))
print('\n Train Data accuracy',accuracy_score(y_train,train_predictions))
print('\n Train Data f1-score for class 1 ',f1_score(y_train,train_predictions,pos_label=1))
print('\n Train Data f1-score for class 0 ',f1_score(y_train,train_predictions,pos_label=0))

# Metrics for Test set
print('\n\n ------------------------------- \n\n')
print('Confusion matrix for test set: \n',confusion_matrix(y_test,test_predictions))
print('\n Test Data accuracy',accuracy_score(y_test,test_predictions))
print('\n Test Data f1-score for class 1 ',f1_score(y_test,test_predictions,pos_label=1))
print('\n Test Data f1-score for class 0 ',f1_score(y_test,test_predictions,pos_label=0))

Confusion matrix for training set: 
 [[278   0]
 [  0 177]]

 Train Data accuracy 1.0

 Train Data f1-score for class 1  1.0

 Train Data f1-score for class 0  1.0


 ------------------------------- 


Confusion matrix for test set: 
 [[78  1]
 [ 3 32]]

 Test Data accuracy 0.9649122807017544

 Test Data f1-score for class 1  0.9411764705882354

 Test Data f1-score for class 0  0.975


## XG Boost

In [33]:
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [34]:
model = XGBClassifier()
model.fit(X_train,y_train)

C:\Users\euise\anaconda3\envs\tf2.2-gpu\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[00:15:34] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [35]:
train_predictions = classifier.predict(X_train)
test_predictions = classifier.predict(X_test)

In [36]:
# Metrics for Training set
print('Confusion matrix for training set: \n',confusion_matrix(y_train,train_predictions))
print('\n Train Data accuracy',accuracy_score(y_train,train_predictions))
print('\n Train Data f1-score for class 1 ',f1_score(y_train,train_predictions,pos_label=1))
print('\n Train Data f1-score for class 0 ',f1_score(y_train,train_predictions,pos_label=0))

# Metrics for Test set
print('\n\n ------------------------------- \n\n')
print('Confusion matrix for test set: \n',confusion_matrix(y_test,test_predictions))
print('\n Test Data accuracy',accuracy_score(y_test,test_predictions))
print('\n Test Data f1-score for class 1 ',f1_score(y_test,test_predictions,pos_label=1))
print('\n Test Data f1-score for class 0 ',f1_score(y_test,test_predictions,pos_label=0))

Confusion matrix for training set: 
 [[278   0]
 [  0 177]]

 Train Data accuracy 1.0

 Train Data f1-score for class 1  1.0

 Train Data f1-score for class 0  1.0


 ------------------------------- 


Confusion matrix for test set: 
 [[78  1]
 [ 3 32]]

 Test Data accuracy 0.9649122807017544

 Test Data f1-score for class 1  0.9411764705882354

 Test Data f1-score for class 0  0.975


## Logistic regression

In [47]:
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression


In [48]:
classifier = linear_model.LogisticRegression()

In [49]:
classifier.fit(X_train,y_train)

C:\Users\euise\anaconda3\envs\tf2.2-gpu\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [50]:
train_predictions = classifier.predict(X_train)
test_predictions = classifier.predict(X_test)

In [51]:
train_predictions

array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,

In [52]:
# Metrics for Training set
print('Confusion matrix for training set: \n',confusion_matrix(y_train,train_predictions))
print('\n Train Data accuracy',accuracy_score(y_train,train_predictions))
print('\n Train Data f1-score for class 1 ',f1_score(y_train,train_predictions,pos_label=1))
print('\n Train Data f1-score for class 0 ',f1_score(y_train,train_predictions,pos_label=0))

# Metrics for Test set
print('\n\n ------------------------------- \n\n')
print('Confusion matrix for test set: \n',confusion_matrix(y_test,test_predictions))
print('\n Test Data accuracy',accuracy_score(y_test,test_predictions))
print('\n Test Data f1-score for class 1 ',f1_score(y_test,test_predictions,pos_label=1))
print('\n Test Data f1-score for class 0 ',f1_score(y_test,test_predictions,pos_label=0))

Confusion matrix for training set: 
 [[268  10]
 [ 15 162]]

 Train Data accuracy 0.945054945054945

 Train Data f1-score for class 1  0.9283667621776504

 Train Data f1-score for class 0  0.9554367201426025


 ------------------------------- 


Confusion matrix for test set: 
 [[74  5]
 [ 3 32]]

 Test Data accuracy 0.9298245614035088

 Test Data f1-score for class 1  0.888888888888889

 Test Data f1-score for class 0  0.9487179487179488


## K-nearest neighbor

In [53]:
from sklearn.neighbors import KNeighborsClassifier


In [57]:
classifier = KNeighborsClassifier(n_neighbors=7)

In [58]:
classifier.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [59]:
train_predictions = classifier.predict(X_train)
test_predictions = classifier.predict(X_test)

In [60]:
# Metrics for Training set
print('Confusion matrix for training set: \n',confusion_matrix(y_train,train_predictions))
print('\n Train Data accuracy',accuracy_score(y_train,train_predictions))
print('\n Train Data f1-score for class 1 ',f1_score(y_train,train_predictions,pos_label=1))
print('\n Train Data f1-score for class 0 ',f1_score(y_train,train_predictions,pos_label=0))

# Metrics for Test set
print('\n\n ------------------------------- \n\n')
print('Confusion matrix for test set: \n',confusion_matrix(y_test,test_predictions))
print('\n Test Data accuracy',accuracy_score(y_test,test_predictions))
print('\n Test Data f1-score for class 1 ',f1_score(y_test,test_predictions,pos_label=1))
print('\n Test Data f1-score for class 0 ',f1_score(y_test,test_predictions,pos_label=0))

Confusion matrix for training set: 
 [[268  10]
 [ 17 160]]

 Train Data accuracy 0.9406593406593406

 Train Data f1-score for class 1  0.9221902017291066

 Train Data f1-score for class 0  0.9520426287744227


 ------------------------------- 


Confusion matrix for test set: 
 [[77  2]
 [ 3 32]]

 Test Data accuracy 0.956140350877193

 Test Data f1-score for class 1  0.9275362318840579

 Test Data f1-score for class 0  0.9685534591194969


## K means

In [61]:
from sklearn.cluster import KMeans

In [64]:
classifier = KMeans(n_clusters=2)
classifier.fit(X_train,y_train)

KMeans(n_clusters=2)

In [65]:
train_predictions = classifier.predict(X_train)
test_predictions = classifier.predict(X_test)

In [66]:
# Metrics for Training set
print('Confusion matrix for training set: \n',confusion_matrix(y_train,train_predictions))
print('\n Train Data accuracy',accuracy_score(y_train,train_predictions))
print('\n Train Data f1-score for class 1 ',f1_score(y_train,train_predictions,pos_label=1))
print('\n Train Data f1-score for class 0 ',f1_score(y_train,train_predictions,pos_label=0))

# Metrics for Test set
print('\n\n ------------------------------- \n\n')
print('Confusion matrix for test set: \n',confusion_matrix(y_test,test_predictions))
print('\n Test Data accuracy',accuracy_score(y_test,test_predictions))
print('\n Test Data f1-score for class 1 ',f1_score(y_test,test_predictions,pos_label=1))
print('\n Test Data f1-score for class 0 ',f1_score(y_test,test_predictions,pos_label=0))

Confusion matrix for training set: 
 [[277   1]
 [ 71 106]]

 Train Data accuracy 0.8417582417582418

 Train Data f1-score for class 1  0.7464788732394367

 Train Data f1-score for class 0  0.8849840255591056


 ------------------------------- 


Confusion matrix for test set: 
 [[79  0]
 [11 24]]

 Test Data accuracy 0.9035087719298246

 Test Data f1-score for class 1  0.8135593220338984

 Test Data f1-score for class 0  0.9349112426035503


## RFECV 

In [1]:
from sklearn.feature_selection import RFECV

In [2]:
model = RandomForestClassifier()
classifier = RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)

NameError: name 'RandomForestClassifier' is not defined